# Gitlab CI docket image
image: node:6.6.0

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/


build:
  stage: build

test:
  stage: test
  script:
    - npm install
    - npm test
  tags:
    - docker

deploy:
  stage: deploy
