# Gitlab CI docket image
image: node:6.6.0

stages:
  - test

cache:
  paths:
    - node_modules/


build:
  stage: build
  script:
    - npm install
  tags:
    - docker

test:
  stage: test
  script:
    - npm install
    - npm test
  tags:
    - docker

deploy:
  stage: deploy
